version: "2"

services:
  live-bot:
    container_name: live-bot
    restart: always
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    volumes:
      - ${PWD}/data:/usr/src/app/data
    build:
      dockerfile: Dockerfile

  flaresolverr:
    container_name: flaresolverr
    ports:
      - 5041:8191
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
